all:
  hosts:
    192.168.97.29:
      ansible_user: jenkins
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ConnectTimeout=30'
